package com.kawasaki.service.provider_service.model;

import java.util.Date;

public class Availability {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PMS_AVAILABILITIES.ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PMS_AVAILABILITIES.PROVIDER_ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private Long providerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PMS_AVAILABILITIES.WEEKDAY
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private Byte weekday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PMS_AVAILABILITIES.START_TIME
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PMS_AVAILABILITIES.END_TIME
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private Date endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMS_AVAILABILITIES.ID
     *
     * @return the value of PMS_AVAILABILITIES.ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMS_AVAILABILITIES.ID
     *
     * @param id the value for PMS_AVAILABILITIES.ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMS_AVAILABILITIES.PROVIDER_ID
     *
     * @return the value of PMS_AVAILABILITIES.PROVIDER_ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public Long getProviderId() {
        return providerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMS_AVAILABILITIES.PROVIDER_ID
     *
     * @param providerId the value for PMS_AVAILABILITIES.PROVIDER_ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setProviderId(Long providerId) {
        this.providerId = providerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMS_AVAILABILITIES.WEEKDAY
     *
     * @return the value of PMS_AVAILABILITIES.WEEKDAY
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public Byte getWeekday() {
        return weekday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMS_AVAILABILITIES.WEEKDAY
     *
     * @param weekday the value for PMS_AVAILABILITIES.WEEKDAY
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setWeekday(Byte weekday) {
        this.weekday = weekday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMS_AVAILABILITIES.START_TIME
     *
     * @return the value of PMS_AVAILABILITIES.START_TIME
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMS_AVAILABILITIES.START_TIME
     *
     * @param startTime the value for PMS_AVAILABILITIES.START_TIME
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMS_AVAILABILITIES.END_TIME
     *
     * @return the value of PMS_AVAILABILITIES.END_TIME
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMS_AVAILABILITIES.END_TIME
     *
     * @param endTime the value for PMS_AVAILABILITIES.END_TIME
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}