package com.kawasaki.service.provider_service.model;

public class Certification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PMS_CERTIFICATIONS.ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PMS_CERTIFICATIONS.PROVIDER_ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    private Long providerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PMS_CERTIFICATIONS.TITLE
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMS_CERTIFICATIONS.ID
     *
     * @return the value of PMS_CERTIFICATIONS.ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMS_CERTIFICATIONS.ID
     *
     * @param id the value for PMS_CERTIFICATIONS.ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMS_CERTIFICATIONS.PROVIDER_ID
     *
     * @return the value of PMS_CERTIFICATIONS.PROVIDER_ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public Long getProviderId() {
        return providerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMS_CERTIFICATIONS.PROVIDER_ID
     *
     * @param providerId the value for PMS_CERTIFICATIONS.PROVIDER_ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public void setProviderId(Long providerId) {
        this.providerId = providerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMS_CERTIFICATIONS.TITLE
     *
     * @return the value of PMS_CERTIFICATIONS.TITLE
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMS_CERTIFICATIONS.TITLE
     *
     * @param title the value for PMS_CERTIFICATIONS.TITLE
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public void setTitle(String title) {
        this.title = title;
    }
}