package com.kawasaki.service.provider_service.model;

import java.util.Date;

public class Provider {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PMS_PROVIDERS.ID
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PMS_PROVIDERS.NAME
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PMS_PROVIDERS.EMAIL
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PMS_PROVIDERS.PHONE
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PMS_PROVIDERS.PASSWORD_HASH
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    private String passwordHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PMS_PROVIDERS.BIO
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    private String bio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PMS_PROVIDERS.CREATED_AT
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PMS_PROVIDERS.UPDATED_AT
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMS_PROVIDERS.ID
     *
     * @return the value of PMS_PROVIDERS.ID
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMS_PROVIDERS.ID
     *
     * @param id the value for PMS_PROVIDERS.ID
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMS_PROVIDERS.NAME
     *
     * @return the value of PMS_PROVIDERS.NAME
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMS_PROVIDERS.NAME
     *
     * @param name the value for PMS_PROVIDERS.NAME
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMS_PROVIDERS.EMAIL
     *
     * @return the value of PMS_PROVIDERS.EMAIL
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMS_PROVIDERS.EMAIL
     *
     * @param email the value for PMS_PROVIDERS.EMAIL
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMS_PROVIDERS.PHONE
     *
     * @return the value of PMS_PROVIDERS.PHONE
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMS_PROVIDERS.PHONE
     *
     * @param phone the value for PMS_PROVIDERS.PHONE
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMS_PROVIDERS.PASSWORD_HASH
     *
     * @return the value of PMS_PROVIDERS.PASSWORD_HASH
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public String getPasswordHash() {
        return passwordHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMS_PROVIDERS.PASSWORD_HASH
     *
     * @param passwordHash the value for PMS_PROVIDERS.PASSWORD_HASH
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMS_PROVIDERS.BIO
     *
     * @return the value of PMS_PROVIDERS.BIO
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public String getBio() {
        return bio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMS_PROVIDERS.BIO
     *
     * @param bio the value for PMS_PROVIDERS.BIO
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public void setBio(String bio) {
        this.bio = bio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMS_PROVIDERS.CREATED_AT
     *
     * @return the value of PMS_PROVIDERS.CREATED_AT
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMS_PROVIDERS.CREATED_AT
     *
     * @param createdAt the value for PMS_PROVIDERS.CREATED_AT
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMS_PROVIDERS.UPDATED_AT
     *
     * @return the value of PMS_PROVIDERS.UPDATED_AT
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMS_PROVIDERS.UPDATED_AT
     *
     * @param updatedAt the value for PMS_PROVIDERS.UPDATED_AT
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}