spring:
  application:
    name: auth-service

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kawasaki.service.common.domain

server:
  port: 99

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka