package com.kawasaki.service.service_service.model;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_CATEGORY.ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_CATEGORY.NAME
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_CATEGORY.PARENT_ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_CATEGORY.LEVEL
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private Byte level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_CATEGORY.ID
     *
     * @return the value of SMS_CATEGORY.ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_CATEGORY.ID
     *
     * @param id the value for SMS_CATEGORY.ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_CATEGORY.NAME
     *
     * @return the value of SMS_CATEGORY.NAME
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_CATEGORY.NAME
     *
     * @param name the value for SMS_CATEGORY.NAME
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_CATEGORY.PARENT_ID
     *
     * @return the value of SMS_CATEGORY.PARENT_ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_CATEGORY.PARENT_ID
     *
     * @param parentId the value for SMS_CATEGORY.PARENT_ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_CATEGORY.LEVEL
     *
     * @return the value of SMS_CATEGORY.LEVEL
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public Byte getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_CATEGORY.LEVEL
     *
     * @param level the value for SMS_CATEGORY.LEVEL
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setLevel(Byte level) {
        this.level = level;
    }
}