package com.kawasaki.service.service_service.model;

public class ServiceAttributeValue {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_SERVICE_ATTRIBUTE_VALUE.ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_SERVICE_ATTRIBUTE_VALUE.SERVICE_ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    private Long serviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_SERVICE_ATTRIBUTE_VALUE.ATTRIBUTE_ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    private Long attributeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_SERVICE_ATTRIBUTE_VALUE.OPTION_ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    private Long optionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_SERVICE_ATTRIBUTE_VALUE.ID
     *
     * @return the value of SMS_SERVICE_ATTRIBUTE_VALUE.ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_SERVICE_ATTRIBUTE_VALUE.ID
     *
     * @param id the value for SMS_SERVICE_ATTRIBUTE_VALUE.ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_SERVICE_ATTRIBUTE_VALUE.SERVICE_ID
     *
     * @return the value of SMS_SERVICE_ATTRIBUTE_VALUE.SERVICE_ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public Long getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_SERVICE_ATTRIBUTE_VALUE.SERVICE_ID
     *
     * @param serviceId the value for SMS_SERVICE_ATTRIBUTE_VALUE.SERVICE_ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public void setServiceId(Long serviceId) {
        this.serviceId = serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_SERVICE_ATTRIBUTE_VALUE.ATTRIBUTE_ID
     *
     * @return the value of SMS_SERVICE_ATTRIBUTE_VALUE.ATTRIBUTE_ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public Long getAttributeId() {
        return attributeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_SERVICE_ATTRIBUTE_VALUE.ATTRIBUTE_ID
     *
     * @param attributeId the value for SMS_SERVICE_ATTRIBUTE_VALUE.ATTRIBUTE_ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public void setAttributeId(Long attributeId) {
        this.attributeId = attributeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_SERVICE_ATTRIBUTE_VALUE.OPTION_ID
     *
     * @return the value of SMS_SERVICE_ATTRIBUTE_VALUE.OPTION_ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public Long getOptionId() {
        return optionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_SERVICE_ATTRIBUTE_VALUE.OPTION_ID
     *
     * @param optionId the value for SMS_SERVICE_ATTRIBUTE_VALUE.OPTION_ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public void setOptionId(Long optionId) {
        this.optionId = optionId;
    }
}