package com.kawasaki.service.service_service.model;

public class ServiceAttribute {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_SERVICE_ATTRIBUTE.ID
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_SERVICE_ATTRIBUTE.CATEGORY_ID
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    private Long categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_SERVICE_ATTRIBUTE.NAME
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_SERVICE_ATTRIBUTE.ID
     *
     * @return the value of SMS_SERVICE_ATTRIBUTE.ID
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_SERVICE_ATTRIBUTE.ID
     *
     * @param id the value for SMS_SERVICE_ATTRIBUTE.ID
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_SERVICE_ATTRIBUTE.CATEGORY_ID
     *
     * @return the value of SMS_SERVICE_ATTRIBUTE.CATEGORY_ID
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_SERVICE_ATTRIBUTE.CATEGORY_ID
     *
     * @param categoryId the value for SMS_SERVICE_ATTRIBUTE.CATEGORY_ID
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_SERVICE_ATTRIBUTE.NAME
     *
     * @return the value of SMS_SERVICE_ATTRIBUTE.NAME
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_SERVICE_ATTRIBUTE.NAME
     *
     * @param name the value for SMS_SERVICE_ATTRIBUTE.NAME
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public void setName(String name) {
        this.name = name;
    }
}