package com.kawasaki.service.service_service.model;

import java.math.BigDecimal;
import java.util.Date;

public class Service {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_SERVICE.ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_SERVICE.PROVIDER_ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private Long providerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_SERVICE.TITLE
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_SERVICE.DESCRIPTION
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_SERVICE.CATEGORY_ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private Long categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_SERVICE.BASE_PRICE
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private BigDecimal basePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_SERVICE.IS_ACTIVE
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private Boolean isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_SERVICE.CREATED_AT
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_SERVICE.UPDATED_AT
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_SERVICE.ID
     *
     * @return the value of SMS_SERVICE.ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_SERVICE.ID
     *
     * @param id the value for SMS_SERVICE.ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_SERVICE.PROVIDER_ID
     *
     * @return the value of SMS_SERVICE.PROVIDER_ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public Long getProviderId() {
        return providerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_SERVICE.PROVIDER_ID
     *
     * @param providerId the value for SMS_SERVICE.PROVIDER_ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setProviderId(Long providerId) {
        this.providerId = providerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_SERVICE.TITLE
     *
     * @return the value of SMS_SERVICE.TITLE
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_SERVICE.TITLE
     *
     * @param title the value for SMS_SERVICE.TITLE
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_SERVICE.DESCRIPTION
     *
     * @return the value of SMS_SERVICE.DESCRIPTION
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_SERVICE.DESCRIPTION
     *
     * @param description the value for SMS_SERVICE.DESCRIPTION
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_SERVICE.CATEGORY_ID
     *
     * @return the value of SMS_SERVICE.CATEGORY_ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_SERVICE.CATEGORY_ID
     *
     * @param categoryId the value for SMS_SERVICE.CATEGORY_ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_SERVICE.BASE_PRICE
     *
     * @return the value of SMS_SERVICE.BASE_PRICE
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public BigDecimal getBasePrice() {
        return basePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_SERVICE.BASE_PRICE
     *
     * @param basePrice the value for SMS_SERVICE.BASE_PRICE
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setBasePrice(BigDecimal basePrice) {
        this.basePrice = basePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_SERVICE.IS_ACTIVE
     *
     * @return the value of SMS_SERVICE.IS_ACTIVE
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_SERVICE.IS_ACTIVE
     *
     * @param isActive the value for SMS_SERVICE.IS_ACTIVE
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_SERVICE.CREATED_AT
     *
     * @return the value of SMS_SERVICE.CREATED_AT
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_SERVICE.CREATED_AT
     *
     * @param createdAt the value for SMS_SERVICE.CREATED_AT
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_SERVICE.UPDATED_AT
     *
     * @return the value of SMS_SERVICE.UPDATED_AT
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_SERVICE.UPDATED_AT
     *
     * @param updatedAt the value for SMS_SERVICE.UPDATED_AT
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}