package com.kawasaki.service.service_service.model;

public class ServiceAttributeOption {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_SERVICE_ATTRIBUTE_OPTION.ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_SERVICE_ATTRIBUTE_OPTION.ATTRIBUTE_ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private Long attributeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_SERVICE_ATTRIBUTE_OPTION.VALUE
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_SERVICE_ATTRIBUTE_OPTION.ID
     *
     * @return the value of SMS_SERVICE_ATTRIBUTE_OPTION.ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_SERVICE_ATTRIBUTE_OPTION.ID
     *
     * @param id the value for SMS_SERVICE_ATTRIBUTE_OPTION.ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_SERVICE_ATTRIBUTE_OPTION.ATTRIBUTE_ID
     *
     * @return the value of SMS_SERVICE_ATTRIBUTE_OPTION.ATTRIBUTE_ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public Long getAttributeId() {
        return attributeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_SERVICE_ATTRIBUTE_OPTION.ATTRIBUTE_ID
     *
     * @param attributeId the value for SMS_SERVICE_ATTRIBUTE_OPTION.ATTRIBUTE_ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setAttributeId(Long attributeId) {
        this.attributeId = attributeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_SERVICE_ATTRIBUTE_OPTION.VALUE
     *
     * @return the value of SMS_SERVICE_ATTRIBUTE_OPTION.VALUE
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_SERVICE_ATTRIBUTE_OPTION.VALUE
     *
     * @param value the value for SMS_SERVICE_ATTRIBUTE_OPTION.VALUE
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setValue(String value) {
        this.value = value;
    }
}