spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:mysql://192.168.56.10/booking_db?useSSL=false&serverTimeZone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 192.168.56.10
    port: 5672
    virtual-host: /

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kawasaki.service.common.domain

server:
  port: 11000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka