package com.kawasaki.service.user_service.model;

public class Address {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_ADDRESSES.ID
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_ADDRESSES.USER_ID
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_ADDRESSES.NAME
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_ADDRESSES.PHONE
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_ADDRESSES.POSTAL_CODE
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    private String postalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_ADDRESSES.PROVINCE
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_ADDRESSES.CITY
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_ADDRESSES.STREET
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    private String street;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_ADDRESSES.UNIT
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_ADDRESSES.IS_DEFAULT
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    private Boolean isDefault;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_ADDRESSES.ID
     *
     * @return the value of UMS_ADDRESSES.ID
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_ADDRESSES.ID
     *
     * @param id the value for UMS_ADDRESSES.ID
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_ADDRESSES.USER_ID
     *
     * @return the value of UMS_ADDRESSES.USER_ID
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_ADDRESSES.USER_ID
     *
     * @param userId the value for UMS_ADDRESSES.USER_ID
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_ADDRESSES.NAME
     *
     * @return the value of UMS_ADDRESSES.NAME
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_ADDRESSES.NAME
     *
     * @param name the value for UMS_ADDRESSES.NAME
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_ADDRESSES.PHONE
     *
     * @return the value of UMS_ADDRESSES.PHONE
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_ADDRESSES.PHONE
     *
     * @param phone the value for UMS_ADDRESSES.PHONE
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_ADDRESSES.POSTAL_CODE
     *
     * @return the value of UMS_ADDRESSES.POSTAL_CODE
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_ADDRESSES.POSTAL_CODE
     *
     * @param postalCode the value for UMS_ADDRESSES.POSTAL_CODE
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_ADDRESSES.PROVINCE
     *
     * @return the value of UMS_ADDRESSES.PROVINCE
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_ADDRESSES.PROVINCE
     *
     * @param province the value for UMS_ADDRESSES.PROVINCE
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_ADDRESSES.CITY
     *
     * @return the value of UMS_ADDRESSES.CITY
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_ADDRESSES.CITY
     *
     * @param city the value for UMS_ADDRESSES.CITY
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_ADDRESSES.STREET
     *
     * @return the value of UMS_ADDRESSES.STREET
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_ADDRESSES.STREET
     *
     * @param street the value for UMS_ADDRESSES.STREET
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public void setStreet(String street) {
        this.street = street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_ADDRESSES.UNIT
     *
     * @return the value of UMS_ADDRESSES.UNIT
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_ADDRESSES.UNIT
     *
     * @param unit the value for UMS_ADDRESSES.UNIT
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_ADDRESSES.IS_DEFAULT
     *
     * @return the value of UMS_ADDRESSES.IS_DEFAULT
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public Boolean getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_ADDRESSES.IS_DEFAULT
     *
     * @param isDefault the value for UMS_ADDRESSES.IS_DEFAULT
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public void setIsDefault(Boolean isDefault) {
        this.isDefault = isDefault;
    }
}