package com.kawasaki.service.user_service.model;

import java.util.Date;

public class SavedServices {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_SAVED_SERVICES.ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_SAVED_SERVICES.USER_ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_SAVED_SERVICES.SERVICE_ID_
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    private Long serviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_SAVED_SERVICES.CREATED_AT
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_SAVED_SERVICES.ID
     *
     * @return the value of UMS_SAVED_SERVICES.ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_SAVED_SERVICES.ID
     *
     * @param id the value for UMS_SAVED_SERVICES.ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_SAVED_SERVICES.USER_ID
     *
     * @return the value of UMS_SAVED_SERVICES.USER_ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_SAVED_SERVICES.USER_ID
     *
     * @param userId the value for UMS_SAVED_SERVICES.USER_ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_SAVED_SERVICES.SERVICE_ID_
     *
     * @return the value of UMS_SAVED_SERVICES.SERVICE_ID_
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public Long getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_SAVED_SERVICES.SERVICE_ID_
     *
     * @param serviceId the value for UMS_SAVED_SERVICES.SERVICE_ID_
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public void setServiceId(Long serviceId) {
        this.serviceId = serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_SAVED_SERVICES.CREATED_AT
     *
     * @return the value of UMS_SAVED_SERVICES.CREATED_AT
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_SAVED_SERVICES.CREATED_AT
     *
     * @param createdAt the value for UMS_SAVED_SERVICES.CREATED_AT
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}