package com.kawasaki.service.user_service.model;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_USERS.ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_USERS.NAME
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_USERS.EMAIL
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_USERS.PHONE
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_USERS.PASSWORD_HASH
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private String passwordHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_USERS.CREATED_AT
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_USERS.UPDATED_AT
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_USERS.ID
     *
     * @return the value of UMS_USERS.ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_USERS.ID
     *
     * @param id the value for UMS_USERS.ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_USERS.NAME
     *
     * @return the value of UMS_USERS.NAME
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_USERS.NAME
     *
     * @param name the value for UMS_USERS.NAME
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_USERS.EMAIL
     *
     * @return the value of UMS_USERS.EMAIL
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_USERS.EMAIL
     *
     * @param email the value for UMS_USERS.EMAIL
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_USERS.PHONE
     *
     * @return the value of UMS_USERS.PHONE
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_USERS.PHONE
     *
     * @param phone the value for UMS_USERS.PHONE
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_USERS.PASSWORD_HASH
     *
     * @return the value of UMS_USERS.PASSWORD_HASH
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public String getPasswordHash() {
        return passwordHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_USERS.PASSWORD_HASH
     *
     * @param passwordHash the value for UMS_USERS.PASSWORD_HASH
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_USERS.CREATED_AT
     *
     * @return the value of UMS_USERS.CREATED_AT
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_USERS.CREATED_AT
     *
     * @param createdAt the value for UMS_USERS.CREATED_AT
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_USERS.UPDATED_AT
     *
     * @return the value of UMS_USERS.UPDATED_AT
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_USERS.UPDATED_AT
     *
     * @param updatedAt the value for UMS_USERS.UPDATED_AT
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}