package com.kawasaki.service.booking_service.mapper;

import com.kawasaki.service.booking_service.model.Booking;
import com.kawasaki.service.booking_service.model.BookingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_BOOKINGS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    long countByExample(BookingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_BOOKINGS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int deleteByExample(BookingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_BOOKINGS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_BOOKINGS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int insert(Booking row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_BOOKINGS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int insertSelective(Booking row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_BOOKINGS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    List<Booking> selectByExample(BookingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_BOOKINGS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    Booking selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_BOOKINGS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int updateByExampleSelective(@Param("row") Booking row, @Param("example") BookingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_BOOKINGS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int updateByExample(@Param("row") Booking row, @Param("example") BookingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_BOOKINGS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int updateByPrimaryKeySelective(Booking row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_BOOKINGS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int updateByPrimaryKey(Booking row);
}