package com.kawasaki.service.booking_service.mapper;

import com.kawasaki.service.booking_service.model.CancelationApplication;
import com.kawasaki.service.booking_service.model.CancelationApplicationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CancelationApplicationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_CANCELATION_APPLICATIONS
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    long countByExample(CancelationApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_CANCELATION_APPLICATIONS
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int deleteByExample(CancelationApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_CANCELATION_APPLICATIONS
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_CANCELATION_APPLICATIONS
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int insert(CancelationApplication row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_CANCELATION_APPLICATIONS
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int insertSelective(CancelationApplication row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_CANCELATION_APPLICATIONS
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    List<CancelationApplication> selectByExample(CancelationApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_CANCELATION_APPLICATIONS
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    CancelationApplication selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_CANCELATION_APPLICATIONS
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int updateByExampleSelective(@Param("row") CancelationApplication row, @Param("example") CancelationApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_CANCELATION_APPLICATIONS
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int updateByExample(@Param("row") CancelationApplication row, @Param("example") CancelationApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_CANCELATION_APPLICATIONS
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int updateByPrimaryKeySelective(CancelationApplication row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_CANCELATION_APPLICATIONS
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int updateByPrimaryKey(CancelationApplication row);
}