package com.kawasaki.service.booking_service.mapper;

import com.kawasaki.service.booking_service.model.Quote;
import com.kawasaki.service.booking_service.model.QuoteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuoteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_QUOTE
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    long countByExample(QuoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_QUOTE
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int deleteByExample(QuoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_QUOTE
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_QUOTE
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int insert(Quote row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_QUOTE
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int insertSelective(Quote row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_QUOTE
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    List<Quote> selectByExample(QuoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_QUOTE
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    Quote selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_QUOTE
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int updateByExampleSelective(@Param("row") Quote row, @Param("example") QuoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_QUOTE
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int updateByExample(@Param("row") Quote row, @Param("example") QuoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_QUOTE
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int updateByPrimaryKeySelective(Quote row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_QUOTE
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int updateByPrimaryKey(Quote row);
}