package com.kawasaki.service.booking_service.mapper;

import com.kawasaki.service.booking_service.model.Request;
import com.kawasaki.service.booking_service.model.RequestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RequestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUESTS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    long countByExample(RequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUESTS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int deleteByExample(RequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUESTS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUESTS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int insert(Request row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUESTS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int insertSelective(Request row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUESTS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    List<Request> selectByExampleWithBLOBs(RequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUESTS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    List<Request> selectByExample(RequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUESTS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    Request selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUESTS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int updateByExampleSelective(@Param("row") Request row, @Param("example") RequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUESTS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int updateByExampleWithBLOBs(@Param("row") Request row, @Param("example") RequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUESTS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int updateByExample(@Param("row") Request row, @Param("example") RequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUESTS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int updateByPrimaryKeySelective(Request row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUESTS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int updateByPrimaryKeyWithBLOBs(Request row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUESTS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int updateByPrimaryKey(Request row);
}