package com.kawasaki.service.booking_service.mapper;

import com.kawasaki.service.booking_service.model.RequestAttrValue;
import com.kawasaki.service.booking_service.model.RequestAttrValueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RequestAttrValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUEST_ATTR_VALUE
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    long countByExample(RequestAttrValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUEST_ATTR_VALUE
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int deleteByExample(RequestAttrValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUEST_ATTR_VALUE
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUEST_ATTR_VALUE
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int insert(RequestAttrValue row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUEST_ATTR_VALUE
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int insertSelective(RequestAttrValue row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUEST_ATTR_VALUE
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    List<RequestAttrValue> selectByExample(RequestAttrValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUEST_ATTR_VALUE
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    RequestAttrValue selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUEST_ATTR_VALUE
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int updateByExampleSelective(@Param("row") RequestAttrValue row, @Param("example") RequestAttrValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUEST_ATTR_VALUE
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int updateByExample(@Param("row") RequestAttrValue row, @Param("example") RequestAttrValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUEST_ATTR_VALUE
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int updateByPrimaryKeySelective(RequestAttrValue row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUEST_ATTR_VALUE
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int updateByPrimaryKey(RequestAttrValue row);
}