package com.kawasaki.service.booking_service.mapper;

import com.kawasaki.service.booking_service.model.RequestAttrOption;
import com.kawasaki.service.booking_service.model.RequestAttrOptionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RequestAttrOptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUEST_ATTR_OPTIONS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    long countByExample(RequestAttrOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUEST_ATTR_OPTIONS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int deleteByExample(RequestAttrOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUEST_ATTR_OPTIONS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUEST_ATTR_OPTIONS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int insert(RequestAttrOption row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUEST_ATTR_OPTIONS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int insertSelective(RequestAttrOption row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUEST_ATTR_OPTIONS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    List<RequestAttrOption> selectByExample(RequestAttrOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUEST_ATTR_OPTIONS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    RequestAttrOption selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUEST_ATTR_OPTIONS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int updateByExampleSelective(@Param("row") RequestAttrOption row, @Param("example") RequestAttrOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUEST_ATTR_OPTIONS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int updateByExample(@Param("row") RequestAttrOption row, @Param("example") RequestAttrOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUEST_ATTR_OPTIONS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int updateByPrimaryKeySelective(RequestAttrOption row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUEST_ATTR_OPTIONS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int updateByPrimaryKey(RequestAttrOption row);
}