package com.kawasaki.service.booking_service.mapper;

import com.kawasaki.service.booking_service.model.RequestAttr;
import com.kawasaki.service.booking_service.model.RequestAttrExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RequestAttrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUEST_ATTRS
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    long countByExample(RequestAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUEST_ATTRS
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int deleteByExample(RequestAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUEST_ATTRS
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUEST_ATTRS
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int insert(RequestAttr row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUEST_ATTRS
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int insertSelective(RequestAttr row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUEST_ATTRS
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    List<RequestAttr> selectByExample(RequestAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUEST_ATTRS
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    RequestAttr selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUEST_ATTRS
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int updateByExampleSelective(@Param("row") RequestAttr row, @Param("example") RequestAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUEST_ATTRS
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int updateByExample(@Param("row") RequestAttr row, @Param("example") RequestAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUEST_ATTRS
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int updateByPrimaryKeySelective(RequestAttr row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BMS_REQUEST_ATTRS
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int updateByPrimaryKey(RequestAttr row);
}