package com.kawasaki.service.user_service.mapper;

import com.kawasaki.service.user_service.model.Address;
import com.kawasaki.service.user_service.model.AddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMS_ADDRESSES
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    long countByExample(AddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMS_ADDRESSES
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int deleteByExample(AddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMS_ADDRESSES
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMS_ADDRESSES
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int insert(Address row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMS_ADDRESSES
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int insertSelective(Address row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMS_ADDRESSES
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    List<Address> selectByExample(AddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMS_ADDRESSES
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    Address selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMS_ADDRESSES
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int updateByExampleSelective(@Param("row") Address row, @Param("example") AddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMS_ADDRESSES
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int updateByExample(@Param("row") Address row, @Param("example") AddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMS_ADDRESSES
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int updateByPrimaryKeySelective(Address row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMS_ADDRESSES
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int updateByPrimaryKey(Address row);
}