package com.kawasaki.service.user_service.mapper;

import com.kawasaki.service.user_service.model.SavedServices;
import com.kawasaki.service.user_service.model.SavedServicesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SavedServicesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMS_SAVED_SERVICES
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    long countByExample(SavedServicesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMS_SAVED_SERVICES
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int deleteByExample(SavedServicesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMS_SAVED_SERVICES
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMS_SAVED_SERVICES
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int insert(SavedServices row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMS_SAVED_SERVICES
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int insertSelective(SavedServices row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMS_SAVED_SERVICES
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    List<SavedServices> selectByExample(SavedServicesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMS_SAVED_SERVICES
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    SavedServices selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMS_SAVED_SERVICES
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int updateByExampleSelective(@Param("row") SavedServices row, @Param("example") SavedServicesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMS_SAVED_SERVICES
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int updateByExample(@Param("row") SavedServices row, @Param("example") SavedServicesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMS_SAVED_SERVICES
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int updateByPrimaryKeySelective(SavedServices row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMS_SAVED_SERVICES
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int updateByPrimaryKey(SavedServices row);
}