package com.kawasaki.service.booking_service.model;

import java.util.Date;

public class Booking {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_BOOKINGS.ID
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_BOOKINGS.USER_ID
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_BOOKINGS.PROVIDER_ID
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    private Long providerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_BOOKINGS.SERVICE_ID
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    private Long serviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_BOOKINGS.BOOKING_NUMBER
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    private String bookingNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_BOOKINGS.SCHEDULED_AT
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    private Date scheduledAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_BOOKINGS.STATUS
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_BOOKINGS.NOTES
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    private String notes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_BOOKINGS.CREATED_AT
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_BOOKINGS.UPDATED_AT
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_BOOKINGS.ID
     *
     * @return the value of BMS_BOOKINGS.ID
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_BOOKINGS.ID
     *
     * @param id the value for BMS_BOOKINGS.ID
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_BOOKINGS.USER_ID
     *
     * @return the value of BMS_BOOKINGS.USER_ID
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_BOOKINGS.USER_ID
     *
     * @param userId the value for BMS_BOOKINGS.USER_ID
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_BOOKINGS.PROVIDER_ID
     *
     * @return the value of BMS_BOOKINGS.PROVIDER_ID
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public Long getProviderId() {
        return providerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_BOOKINGS.PROVIDER_ID
     *
     * @param providerId the value for BMS_BOOKINGS.PROVIDER_ID
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public void setProviderId(Long providerId) {
        this.providerId = providerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_BOOKINGS.SERVICE_ID
     *
     * @return the value of BMS_BOOKINGS.SERVICE_ID
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public Long getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_BOOKINGS.SERVICE_ID
     *
     * @param serviceId the value for BMS_BOOKINGS.SERVICE_ID
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public void setServiceId(Long serviceId) {
        this.serviceId = serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_BOOKINGS.BOOKING_NUMBER
     *
     * @return the value of BMS_BOOKINGS.BOOKING_NUMBER
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public String getBookingNumber() {
        return bookingNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_BOOKINGS.BOOKING_NUMBER
     *
     * @param bookingNumber the value for BMS_BOOKINGS.BOOKING_NUMBER
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public void setBookingNumber(String bookingNumber) {
        this.bookingNumber = bookingNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_BOOKINGS.SCHEDULED_AT
     *
     * @return the value of BMS_BOOKINGS.SCHEDULED_AT
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public Date getScheduledAt() {
        return scheduledAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_BOOKINGS.SCHEDULED_AT
     *
     * @param scheduledAt the value for BMS_BOOKINGS.SCHEDULED_AT
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public void setScheduledAt(Date scheduledAt) {
        this.scheduledAt = scheduledAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_BOOKINGS.STATUS
     *
     * @return the value of BMS_BOOKINGS.STATUS
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_BOOKINGS.STATUS
     *
     * @param status the value for BMS_BOOKINGS.STATUS
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_BOOKINGS.NOTES
     *
     * @return the value of BMS_BOOKINGS.NOTES
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_BOOKINGS.NOTES
     *
     * @param notes the value for BMS_BOOKINGS.NOTES
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_BOOKINGS.CREATED_AT
     *
     * @return the value of BMS_BOOKINGS.CREATED_AT
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_BOOKINGS.CREATED_AT
     *
     * @param createdAt the value for BMS_BOOKINGS.CREATED_AT
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_BOOKINGS.UPDATED_AT
     *
     * @return the value of BMS_BOOKINGS.UPDATED_AT
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_BOOKINGS.UPDATED_AT
     *
     * @param updatedAt the value for BMS_BOOKINGS.UPDATED_AT
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}