package com.kawasaki.service.booking_service.model;

import java.util.Date;

public class CancelationApplication {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_CANCELATION_APPLICATIONS.ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_CANCELATION_APPLICATIONS.BOOKING_ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private Long bookingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_CANCELATION_APPLICATIONS.USER_ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_CANCELATION_APPLICATIONS.REASON
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_CANCELATION_APPLICATIONS.STATUS
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_CANCELATION_APPLICATIONS.CREATED_AT
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_CANCELATION_APPLICATIONS.UPDATED_AT
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_CANCELATION_APPLICATIONS.ID
     *
     * @return the value of BMS_CANCELATION_APPLICATIONS.ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_CANCELATION_APPLICATIONS.ID
     *
     * @param id the value for BMS_CANCELATION_APPLICATIONS.ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_CANCELATION_APPLICATIONS.BOOKING_ID
     *
     * @return the value of BMS_CANCELATION_APPLICATIONS.BOOKING_ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public Long getBookingId() {
        return bookingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_CANCELATION_APPLICATIONS.BOOKING_ID
     *
     * @param bookingId the value for BMS_CANCELATION_APPLICATIONS.BOOKING_ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setBookingId(Long bookingId) {
        this.bookingId = bookingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_CANCELATION_APPLICATIONS.USER_ID
     *
     * @return the value of BMS_CANCELATION_APPLICATIONS.USER_ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_CANCELATION_APPLICATIONS.USER_ID
     *
     * @param userId the value for BMS_CANCELATION_APPLICATIONS.USER_ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_CANCELATION_APPLICATIONS.REASON
     *
     * @return the value of BMS_CANCELATION_APPLICATIONS.REASON
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_CANCELATION_APPLICATIONS.REASON
     *
     * @param reason the value for BMS_CANCELATION_APPLICATIONS.REASON
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_CANCELATION_APPLICATIONS.STATUS
     *
     * @return the value of BMS_CANCELATION_APPLICATIONS.STATUS
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_CANCELATION_APPLICATIONS.STATUS
     *
     * @param status the value for BMS_CANCELATION_APPLICATIONS.STATUS
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_CANCELATION_APPLICATIONS.CREATED_AT
     *
     * @return the value of BMS_CANCELATION_APPLICATIONS.CREATED_AT
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_CANCELATION_APPLICATIONS.CREATED_AT
     *
     * @param createdAt the value for BMS_CANCELATION_APPLICATIONS.CREATED_AT
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_CANCELATION_APPLICATIONS.UPDATED_AT
     *
     * @return the value of BMS_CANCELATION_APPLICATIONS.UPDATED_AT
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_CANCELATION_APPLICATIONS.UPDATED_AT
     *
     * @param updatedAt the value for BMS_CANCELATION_APPLICATIONS.UPDATED_AT
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}