package com.kawasaki.service.booking_service.model;

import java.math.BigDecimal;
import java.util.Date;

public class Quote {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_QUOTE.ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_QUOTE.REQUEST_ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    private Long requestId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_QUOTE.USER_ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_QUOTE.PROVIDER_ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    private Long providerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_QUOTE.PRICE
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_QUOTE.STATUS
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_QUOTE.CREATED_AT
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_QUOTE.UPDATED_AT
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_QUOTE.ID
     *
     * @return the value of BMS_QUOTE.ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_QUOTE.ID
     *
     * @param id the value for BMS_QUOTE.ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_QUOTE.REQUEST_ID
     *
     * @return the value of BMS_QUOTE.REQUEST_ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public Long getRequestId() {
        return requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_QUOTE.REQUEST_ID
     *
     * @param requestId the value for BMS_QUOTE.REQUEST_ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public void setRequestId(Long requestId) {
        this.requestId = requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_QUOTE.USER_ID
     *
     * @return the value of BMS_QUOTE.USER_ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_QUOTE.USER_ID
     *
     * @param userId the value for BMS_QUOTE.USER_ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_QUOTE.PROVIDER_ID
     *
     * @return the value of BMS_QUOTE.PROVIDER_ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public Long getProviderId() {
        return providerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_QUOTE.PROVIDER_ID
     *
     * @param providerId the value for BMS_QUOTE.PROVIDER_ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public void setProviderId(Long providerId) {
        this.providerId = providerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_QUOTE.PRICE
     *
     * @return the value of BMS_QUOTE.PRICE
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_QUOTE.PRICE
     *
     * @param price the value for BMS_QUOTE.PRICE
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_QUOTE.STATUS
     *
     * @return the value of BMS_QUOTE.STATUS
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_QUOTE.STATUS
     *
     * @param status the value for BMS_QUOTE.STATUS
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_QUOTE.CREATED_AT
     *
     * @return the value of BMS_QUOTE.CREATED_AT
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_QUOTE.CREATED_AT
     *
     * @param createdAt the value for BMS_QUOTE.CREATED_AT
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_QUOTE.UPDATED_AT
     *
     * @return the value of BMS_QUOTE.UPDATED_AT
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_QUOTE.UPDATED_AT
     *
     * @param updatedAt the value for BMS_QUOTE.UPDATED_AT
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}