package com.kawasaki.service.booking_service.model;

public class RequestAttr {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_REQUEST_ATTRS.ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_REQUEST_ATTRS.CATEGORY_ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    private Long categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_REQUEST_ATTRS.NAME
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_REQUEST_ATTRS.ID
     *
     * @return the value of BMS_REQUEST_ATTRS.ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_REQUEST_ATTRS.ID
     *
     * @param id the value for BMS_REQUEST_ATTRS.ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_REQUEST_ATTRS.CATEGORY_ID
     *
     * @return the value of BMS_REQUEST_ATTRS.CATEGORY_ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_REQUEST_ATTRS.CATEGORY_ID
     *
     * @param categoryId the value for BMS_REQUEST_ATTRS.CATEGORY_ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_REQUEST_ATTRS.NAME
     *
     * @return the value of BMS_REQUEST_ATTRS.NAME
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_REQUEST_ATTRS.NAME
     *
     * @param name the value for BMS_REQUEST_ATTRS.NAME
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public void setName(String name) {
        this.name = name;
    }
}