package com.kawasaki.service.booking_service.model;

import java.math.BigDecimal;
import java.util.Date;

public class Request {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_REQUESTS.ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_REQUESTS.USER_ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_REQUESTS.SERVICE_ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    private Long serviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_REQUESTS.PROVIDER_ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    private Long providerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_REQUESTS.CATEGORY_ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    private Long categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_REQUESTS.CREATED_AT
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_REQUESTS.UPDATED_AT
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_REQUESTS.STATUS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_REQUESTS.TIME_PREFERENCE
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    private Byte timePreference;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_REQUESTS.BUDGET
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    private BigDecimal budget;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_REQUESTS.NOTE
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_REQUESTS.ID
     *
     * @return the value of BMS_REQUESTS.ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_REQUESTS.ID
     *
     * @param id the value for BMS_REQUESTS.ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_REQUESTS.USER_ID
     *
     * @return the value of BMS_REQUESTS.USER_ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_REQUESTS.USER_ID
     *
     * @param userId the value for BMS_REQUESTS.USER_ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_REQUESTS.SERVICE_ID
     *
     * @return the value of BMS_REQUESTS.SERVICE_ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public Long getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_REQUESTS.SERVICE_ID
     *
     * @param serviceId the value for BMS_REQUESTS.SERVICE_ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public void setServiceId(Long serviceId) {
        this.serviceId = serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_REQUESTS.PROVIDER_ID
     *
     * @return the value of BMS_REQUESTS.PROVIDER_ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public Long getProviderId() {
        return providerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_REQUESTS.PROVIDER_ID
     *
     * @param providerId the value for BMS_REQUESTS.PROVIDER_ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public void setProviderId(Long providerId) {
        this.providerId = providerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_REQUESTS.CATEGORY_ID
     *
     * @return the value of BMS_REQUESTS.CATEGORY_ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_REQUESTS.CATEGORY_ID
     *
     * @param categoryId the value for BMS_REQUESTS.CATEGORY_ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_REQUESTS.CREATED_AT
     *
     * @return the value of BMS_REQUESTS.CREATED_AT
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_REQUESTS.CREATED_AT
     *
     * @param createdAt the value for BMS_REQUESTS.CREATED_AT
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_REQUESTS.UPDATED_AT
     *
     * @return the value of BMS_REQUESTS.UPDATED_AT
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_REQUESTS.UPDATED_AT
     *
     * @param updatedAt the value for BMS_REQUESTS.UPDATED_AT
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_REQUESTS.STATUS
     *
     * @return the value of BMS_REQUESTS.STATUS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_REQUESTS.STATUS
     *
     * @param status the value for BMS_REQUESTS.STATUS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_REQUESTS.TIME_PREFERENCE
     *
     * @return the value of BMS_REQUESTS.TIME_PREFERENCE
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public Byte getTimePreference() {
        return timePreference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_REQUESTS.TIME_PREFERENCE
     *
     * @param timePreference the value for BMS_REQUESTS.TIME_PREFERENCE
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public void setTimePreference(Byte timePreference) {
        this.timePreference = timePreference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_REQUESTS.BUDGET
     *
     * @return the value of BMS_REQUESTS.BUDGET
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public BigDecimal getBudget() {
        return budget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_REQUESTS.BUDGET
     *
     * @param budget the value for BMS_REQUESTS.BUDGET
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public void setBudget(BigDecimal budget) {
        this.budget = budget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_REQUESTS.NOTE
     *
     * @return the value of BMS_REQUESTS.NOTE
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_REQUESTS.NOTE
     *
     * @param note the value for BMS_REQUESTS.NOTE
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public void setNote(String note) {
        this.note = note;
    }
}