package com.kawasaki.service.booking_service.model;

public class RequestAttrValue {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_REQUEST_ATTR_VALUE.ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_REQUEST_ATTR_VALUE.REQUEST_ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    private Long requestId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_REQUEST_ATTR_VALUE.ATTR_ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    private Long attrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_REQUEST_ATTR_VALUE.OPTION_ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    private Long optionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_REQUEST_ATTR_VALUE.ID
     *
     * @return the value of BMS_REQUEST_ATTR_VALUE.ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_REQUEST_ATTR_VALUE.ID
     *
     * @param id the value for BMS_REQUEST_ATTR_VALUE.ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_REQUEST_ATTR_VALUE.REQUEST_ID
     *
     * @return the value of BMS_REQUEST_ATTR_VALUE.REQUEST_ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public Long getRequestId() {
        return requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_REQUEST_ATTR_VALUE.REQUEST_ID
     *
     * @param requestId the value for BMS_REQUEST_ATTR_VALUE.REQUEST_ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public void setRequestId(Long requestId) {
        this.requestId = requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_REQUEST_ATTR_VALUE.ATTR_ID
     *
     * @return the value of BMS_REQUEST_ATTR_VALUE.ATTR_ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public Long getAttrId() {
        return attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_REQUEST_ATTR_VALUE.ATTR_ID
     *
     * @param attrId the value for BMS_REQUEST_ATTR_VALUE.ATTR_ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public void setAttrId(Long attrId) {
        this.attrId = attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_REQUEST_ATTR_VALUE.OPTION_ID
     *
     * @return the value of BMS_REQUEST_ATTR_VALUE.OPTION_ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public Long getOptionId() {
        return optionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_REQUEST_ATTR_VALUE.OPTION_ID
     *
     * @param optionId the value for BMS_REQUEST_ATTR_VALUE.OPTION_ID
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    public void setOptionId(Long optionId) {
        this.optionId = optionId;
    }
}