package com.kawasaki.service.booking_service.model;

public class RequestAttrOption {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_REQUEST_ATTR_OPTIONS.ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_REQUEST_ATTR_OPTIONS.ATTR_ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    private Long attrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BMS_REQUEST_ATTR_OPTIONS.NAME
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_REQUEST_ATTR_OPTIONS.ID
     *
     * @return the value of BMS_REQUEST_ATTR_OPTIONS.ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_REQUEST_ATTR_OPTIONS.ID
     *
     * @param id the value for BMS_REQUEST_ATTR_OPTIONS.ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_REQUEST_ATTR_OPTIONS.ATTR_ID
     *
     * @return the value of BMS_REQUEST_ATTR_OPTIONS.ATTR_ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public Long getAttrId() {
        return attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_REQUEST_ATTR_OPTIONS.ATTR_ID
     *
     * @param attrId the value for BMS_REQUEST_ATTR_OPTIONS.ATTR_ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public void setAttrId(Long attrId) {
        this.attrId = attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BMS_REQUEST_ATTR_OPTIONS.NAME
     *
     * @return the value of BMS_REQUEST_ATTR_OPTIONS.NAME
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BMS_REQUEST_ATTR_OPTIONS.NAME
     *
     * @param name the value for BMS_REQUEST_ATTR_OPTIONS.NAME
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public void setName(String name) {
        this.name = name;
    }
}