package com.kawasaki.service.service_service.mapper;

import com.kawasaki.service.service_service.model.Category;
import com.kawasaki.service.service_service.model.CategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_CATEGORY
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    long countByExample(CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_CATEGORY
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int deleteByExample(CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_CATEGORY
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_CATEGORY
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int insert(Category row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_CATEGORY
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int insertSelective(Category row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_CATEGORY
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    List<Category> selectByExample(CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_CATEGORY
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    Category selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_CATEGORY
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int updateByExampleSelective(@Param("row") Category row, @Param("example") CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_CATEGORY
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int updateByExample(@Param("row") Category row, @Param("example") CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_CATEGORY
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int updateByPrimaryKeySelective(Category row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_CATEGORY
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int updateByPrimaryKey(Category row);
}