package com.kawasaki.service.service_service.mapper;

import com.kawasaki.service.service_service.model.ServiceAttributeOption;
import com.kawasaki.service.service_service.model.ServiceAttributeOptionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ServiceAttributeOptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE_ATTRIBUTE_OPTION
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    long countByExample(ServiceAttributeOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE_ATTRIBUTE_OPTION
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int deleteByExample(ServiceAttributeOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE_ATTRIBUTE_OPTION
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE_ATTRIBUTE_OPTION
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int insert(ServiceAttributeOption row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE_ATTRIBUTE_OPTION
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int insertSelective(ServiceAttributeOption row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE_ATTRIBUTE_OPTION
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    List<ServiceAttributeOption> selectByExample(ServiceAttributeOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE_ATTRIBUTE_OPTION
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    ServiceAttributeOption selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE_ATTRIBUTE_OPTION
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int updateByExampleSelective(@Param("row") ServiceAttributeOption row, @Param("example") ServiceAttributeOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE_ATTRIBUTE_OPTION
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int updateByExample(@Param("row") ServiceAttributeOption row, @Param("example") ServiceAttributeOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE_ATTRIBUTE_OPTION
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int updateByPrimaryKeySelective(ServiceAttributeOption row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE_ATTRIBUTE_OPTION
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int updateByPrimaryKey(ServiceAttributeOption row);
}