package com.kawasaki.service.service_service.mapper;

import com.kawasaki.service.service_service.model.ServiceAttribute;
import com.kawasaki.service.service_service.model.ServiceAttributeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ServiceAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE_ATTRIBUTE
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    long countByExample(ServiceAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE_ATTRIBUTE
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int deleteByExample(ServiceAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE_ATTRIBUTE
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE_ATTRIBUTE
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int insert(ServiceAttribute row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE_ATTRIBUTE
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int insertSelective(ServiceAttribute row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE_ATTRIBUTE
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    List<ServiceAttribute> selectByExample(ServiceAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE_ATTRIBUTE
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    ServiceAttribute selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE_ATTRIBUTE
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int updateByExampleSelective(@Param("row") ServiceAttribute row, @Param("example") ServiceAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE_ATTRIBUTE
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int updateByExample(@Param("row") ServiceAttribute row, @Param("example") ServiceAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE_ATTRIBUTE
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int updateByPrimaryKeySelective(ServiceAttribute row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE_ATTRIBUTE
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int updateByPrimaryKey(ServiceAttribute row);
}