package com.kawasaki.service.service_service.mapper;

import com.kawasaki.service.service_service.model.ServiceAttributeValue;
import com.kawasaki.service.service_service.model.ServiceAttributeValueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ServiceAttributeValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE_ATTRIBUTE_VALUE
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    long countByExample(ServiceAttributeValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE_ATTRIBUTE_VALUE
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int deleteByExample(ServiceAttributeValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE_ATTRIBUTE_VALUE
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE_ATTRIBUTE_VALUE
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int insert(ServiceAttributeValue row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE_ATTRIBUTE_VALUE
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int insertSelective(ServiceAttributeValue row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE_ATTRIBUTE_VALUE
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    List<ServiceAttributeValue> selectByExample(ServiceAttributeValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE_ATTRIBUTE_VALUE
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    ServiceAttributeValue selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE_ATTRIBUTE_VALUE
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int updateByExampleSelective(@Param("row") ServiceAttributeValue row, @Param("example") ServiceAttributeValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE_ATTRIBUTE_VALUE
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int updateByExample(@Param("row") ServiceAttributeValue row, @Param("example") ServiceAttributeValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE_ATTRIBUTE_VALUE
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int updateByPrimaryKeySelective(ServiceAttributeValue row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE_ATTRIBUTE_VALUE
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int updateByPrimaryKey(ServiceAttributeValue row);
}