package com.kawasaki.service.service_service.mapper;

import com.kawasaki.service.service_service.model.Service;
import com.kawasaki.service.service_service.model.ServiceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ServiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    long countByExample(ServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int deleteByExample(ServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int insert(Service row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int insertSelective(Service row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    List<Service> selectByExample(ServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    Service selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int updateByExampleSelective(@Param("row") Service row, @Param("example") ServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int updateByExample(@Param("row") Service row, @Param("example") ServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int updateByPrimaryKeySelective(Service row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_SERVICE
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int updateByPrimaryKey(Service row);
}