spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://192.168.56.10/order_db?useSSL=false&serverTimeZone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 192.168.56.10
      port: 6379

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kawasaki.service.common.domain

server:
  port: 12000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka