package com.kawasaki.service.provider_service.mapper;

import com.kawasaki.service.provider_service.model.Availability;
import com.kawasaki.service.provider_service.model.AvailabilityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AvailabilityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMS_AVAILABILITIES
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    long countByExample(AvailabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMS_AVAILABILITIES
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int deleteByExample(AvailabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMS_AVAILABILITIES
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMS_AVAILABILITIES
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int insert(Availability row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMS_AVAILABILITIES
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int insertSelective(Availability row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMS_AVAILABILITIES
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    List<Availability> selectByExample(AvailabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMS_AVAILABILITIES
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    Availability selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMS_AVAILABILITIES
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int updateByExampleSelective(@Param("row") Availability row, @Param("example") AvailabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMS_AVAILABILITIES
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int updateByExample(@Param("row") Availability row, @Param("example") AvailabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMS_AVAILABILITIES
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int updateByPrimaryKeySelective(Availability row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMS_AVAILABILITIES
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int updateByPrimaryKey(Availability row);
}