package com.kawasaki.service.provider_service.mapper;

import com.kawasaki.service.provider_service.model.Certification;
import com.kawasaki.service.provider_service.model.CertificationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CertificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMS_CERTIFICATIONS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    long countByExample(CertificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMS_CERTIFICATIONS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int deleteByExample(CertificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMS_CERTIFICATIONS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMS_CERTIFICATIONS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int insert(Certification row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMS_CERTIFICATIONS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int insertSelective(Certification row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMS_CERTIFICATIONS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    List<Certification> selectByExample(CertificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMS_CERTIFICATIONS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    Certification selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMS_CERTIFICATIONS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int updateByExampleSelective(@Param("row") Certification row, @Param("example") CertificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMS_CERTIFICATIONS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int updateByExample(@Param("row") Certification row, @Param("example") CertificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMS_CERTIFICATIONS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int updateByPrimaryKeySelective(Certification row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMS_CERTIFICATIONS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    int updateByPrimaryKey(Certification row);
}