package com.kawasaki.service.provider_service.mapper;

import com.kawasaki.service.provider_service.model.Provider;
import com.kawasaki.service.provider_service.model.ProviderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProviderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMS_PROVIDERS
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    long countByExample(ProviderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMS_PROVIDERS
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int deleteByExample(ProviderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMS_PROVIDERS
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMS_PROVIDERS
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int insert(Provider row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMS_PROVIDERS
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int insertSelective(Provider row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMS_PROVIDERS
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    List<Provider> selectByExample(ProviderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMS_PROVIDERS
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    Provider selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMS_PROVIDERS
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int updateByExampleSelective(@Param("row") Provider row, @Param("example") ProviderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMS_PROVIDERS
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int updateByExample(@Param("row") Provider row, @Param("example") ProviderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMS_PROVIDERS
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int updateByPrimaryKeySelective(Provider row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMS_PROVIDERS
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int updateByPrimaryKey(Provider row);
}