package com.kawasaki.service.order_service.model;

import java.math.BigDecimal;
import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_ORDERS.ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_ORDERS.USER_ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_ORDERS.ORDER_NUMBER
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private String orderNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_ORDERS.QUOTE_ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private Long quoteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_ORDERS.SERVICE_ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private Long serviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_ORDERS.STATUS
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_ORDERS.TOTAL
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private BigDecimal total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_ORDERS.CREATED_AT
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_ORDERS.PAID_AT
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private Date paidAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_ORDERS.UPDATED_AT
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_ORDERS.REQUEST_ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private Long requestId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_ORDERS.ID
     *
     * @return the value of OMS_ORDERS.ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_ORDERS.ID
     *
     * @param id the value for OMS_ORDERS.ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_ORDERS.USER_ID
     *
     * @return the value of OMS_ORDERS.USER_ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_ORDERS.USER_ID
     *
     * @param userId the value for OMS_ORDERS.USER_ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_ORDERS.ORDER_NUMBER
     *
     * @return the value of OMS_ORDERS.ORDER_NUMBER
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_ORDERS.ORDER_NUMBER
     *
     * @param orderNumber the value for OMS_ORDERS.ORDER_NUMBER
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_ORDERS.QUOTE_ID
     *
     * @return the value of OMS_ORDERS.QUOTE_ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public Long getQuoteId() {
        return quoteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_ORDERS.QUOTE_ID
     *
     * @param quoteId the value for OMS_ORDERS.QUOTE_ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setQuoteId(Long quoteId) {
        this.quoteId = quoteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_ORDERS.SERVICE_ID
     *
     * @return the value of OMS_ORDERS.SERVICE_ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public Long getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_ORDERS.SERVICE_ID
     *
     * @param serviceId the value for OMS_ORDERS.SERVICE_ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setServiceId(Long serviceId) {
        this.serviceId = serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_ORDERS.STATUS
     *
     * @return the value of OMS_ORDERS.STATUS
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_ORDERS.STATUS
     *
     * @param status the value for OMS_ORDERS.STATUS
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_ORDERS.TOTAL
     *
     * @return the value of OMS_ORDERS.TOTAL
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_ORDERS.TOTAL
     *
     * @param total the value for OMS_ORDERS.TOTAL
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_ORDERS.CREATED_AT
     *
     * @return the value of OMS_ORDERS.CREATED_AT
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_ORDERS.CREATED_AT
     *
     * @param createdAt the value for OMS_ORDERS.CREATED_AT
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_ORDERS.PAID_AT
     *
     * @return the value of OMS_ORDERS.PAID_AT
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public Date getPaidAt() {
        return paidAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_ORDERS.PAID_AT
     *
     * @param paidAt the value for OMS_ORDERS.PAID_AT
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setPaidAt(Date paidAt) {
        this.paidAt = paidAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_ORDERS.UPDATED_AT
     *
     * @return the value of OMS_ORDERS.UPDATED_AT
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_ORDERS.UPDATED_AT
     *
     * @param updatedAt the value for OMS_ORDERS.UPDATED_AT
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_ORDERS.REQUEST_ID
     *
     * @return the value of OMS_ORDERS.REQUEST_ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public Long getRequestId() {
        return requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_ORDERS.REQUEST_ID
     *
     * @param requestId the value for OMS_ORDERS.REQUEST_ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setRequestId(Long requestId) {
        this.requestId = requestId;
    }
}