package com.kawasaki.service.order_service.model;

import java.math.BigDecimal;
import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_ORDERS.ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_ORDERS.USER_ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_ORDERS.ORDER_NUMBER
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    private String orderNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_ORDERS.BOOKING_ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    private Long bookingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_ORDERS.SERVICE_ID_
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    private Long serviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_ORDERS.STATUS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_ORDERS.TOTAL
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    private BigDecimal total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_ORDERS.CREATED_AT
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_ORDERS.PAID_AT
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    private Date paidAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_ORDERS.UPDATED_AT
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_ORDERS.ID
     *
     * @return the value of OMS_ORDERS.ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_ORDERS.ID
     *
     * @param id the value for OMS_ORDERS.ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_ORDERS.USER_ID
     *
     * @return the value of OMS_ORDERS.USER_ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_ORDERS.USER_ID
     *
     * @param userId the value for OMS_ORDERS.USER_ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_ORDERS.ORDER_NUMBER
     *
     * @return the value of OMS_ORDERS.ORDER_NUMBER
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_ORDERS.ORDER_NUMBER
     *
     * @param orderNumber the value for OMS_ORDERS.ORDER_NUMBER
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_ORDERS.BOOKING_ID
     *
     * @return the value of OMS_ORDERS.BOOKING_ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public Long getBookingId() {
        return bookingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_ORDERS.BOOKING_ID
     *
     * @param bookingId the value for OMS_ORDERS.BOOKING_ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public void setBookingId(Long bookingId) {
        this.bookingId = bookingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_ORDERS.SERVICE_ID_
     *
     * @return the value of OMS_ORDERS.SERVICE_ID_
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public Long getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_ORDERS.SERVICE_ID_
     *
     * @param serviceId the value for OMS_ORDERS.SERVICE_ID_
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public void setServiceId(Long serviceId) {
        this.serviceId = serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_ORDERS.STATUS
     *
     * @return the value of OMS_ORDERS.STATUS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_ORDERS.STATUS
     *
     * @param status the value for OMS_ORDERS.STATUS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_ORDERS.TOTAL
     *
     * @return the value of OMS_ORDERS.TOTAL
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_ORDERS.TOTAL
     *
     * @param total the value for OMS_ORDERS.TOTAL
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_ORDERS.CREATED_AT
     *
     * @return the value of OMS_ORDERS.CREATED_AT
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_ORDERS.CREATED_AT
     *
     * @param createdAt the value for OMS_ORDERS.CREATED_AT
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_ORDERS.PAID_AT
     *
     * @return the value of OMS_ORDERS.PAID_AT
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public Date getPaidAt() {
        return paidAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_ORDERS.PAID_AT
     *
     * @param paidAt the value for OMS_ORDERS.PAID_AT
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public void setPaidAt(Date paidAt) {
        this.paidAt = paidAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_ORDERS.UPDATED_AT
     *
     * @return the value of OMS_ORDERS.UPDATED_AT
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_ORDERS.UPDATED_AT
     *
     * @param updatedAt the value for OMS_ORDERS.UPDATED_AT
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}