package com.kawasaki.service.order_service.model;

import java.math.BigDecimal;
import java.util.Date;

public class Payment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_PAYMENTS.ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_PAYMENTS.ORDER_ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_PAYMENTS.STATUS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_PAYMENTS.PAYMENT_METHOD
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    private Byte paymentMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_PAYMENTS.TOTAL
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    private BigDecimal total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_PAYMENTS.INITIATED_AT
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    private Date initiatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_PAYMENTS.CONFIRMED_AT
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    private Date confirmedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_PAYMENTS.ID
     *
     * @return the value of OMS_PAYMENTS.ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_PAYMENTS.ID
     *
     * @param id the value for OMS_PAYMENTS.ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_PAYMENTS.ORDER_ID
     *
     * @return the value of OMS_PAYMENTS.ORDER_ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_PAYMENTS.ORDER_ID
     *
     * @param orderId the value for OMS_PAYMENTS.ORDER_ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_PAYMENTS.STATUS
     *
     * @return the value of OMS_PAYMENTS.STATUS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_PAYMENTS.STATUS
     *
     * @param status the value for OMS_PAYMENTS.STATUS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_PAYMENTS.PAYMENT_METHOD
     *
     * @return the value of OMS_PAYMENTS.PAYMENT_METHOD
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public Byte getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_PAYMENTS.PAYMENT_METHOD
     *
     * @param paymentMethod the value for OMS_PAYMENTS.PAYMENT_METHOD
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public void setPaymentMethod(Byte paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_PAYMENTS.TOTAL
     *
     * @return the value of OMS_PAYMENTS.TOTAL
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_PAYMENTS.TOTAL
     *
     * @param total the value for OMS_PAYMENTS.TOTAL
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_PAYMENTS.INITIATED_AT
     *
     * @return the value of OMS_PAYMENTS.INITIATED_AT
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public Date getInitiatedAt() {
        return initiatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_PAYMENTS.INITIATED_AT
     *
     * @param initiatedAt the value for OMS_PAYMENTS.INITIATED_AT
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public void setInitiatedAt(Date initiatedAt) {
        this.initiatedAt = initiatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_PAYMENTS.CONFIRMED_AT
     *
     * @return the value of OMS_PAYMENTS.CONFIRMED_AT
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public Date getConfirmedAt() {
        return confirmedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_PAYMENTS.CONFIRMED_AT
     *
     * @param confirmedAt the value for OMS_PAYMENTS.CONFIRMED_AT
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public void setConfirmedAt(Date confirmedAt) {
        this.confirmedAt = confirmedAt;
    }
}