package com.kawasaki.service.order_service.model;

import java.math.BigDecimal;
import java.util.Date;

public class RefundApplication {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_REFUND_APPLICATIONS.ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_REFUND_APPLICATIONS.ORDER_ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_REFUND_APPLICATIONS.SERVICE_ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private Long serviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_REFUND_APPLICATIONS.ORDER_NUMBER
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private String orderNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_REFUND_APPLICATIONS.STATUS
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_REFUND_APPLICATIONS.REFUND_TOTAL
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private BigDecimal refundTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_REFUND_APPLICATIONS.REASON
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_REFUND_APPLICATIONS.CREATED_AT
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_REFUND_APPLICATIONS.UPDATED_AT
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_REFUND_APPLICATIONS.ID
     *
     * @return the value of OMS_REFUND_APPLICATIONS.ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_REFUND_APPLICATIONS.ID
     *
     * @param id the value for OMS_REFUND_APPLICATIONS.ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_REFUND_APPLICATIONS.ORDER_ID
     *
     * @return the value of OMS_REFUND_APPLICATIONS.ORDER_ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_REFUND_APPLICATIONS.ORDER_ID
     *
     * @param orderId the value for OMS_REFUND_APPLICATIONS.ORDER_ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_REFUND_APPLICATIONS.SERVICE_ID
     *
     * @return the value of OMS_REFUND_APPLICATIONS.SERVICE_ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public Long getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_REFUND_APPLICATIONS.SERVICE_ID
     *
     * @param serviceId the value for OMS_REFUND_APPLICATIONS.SERVICE_ID
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setServiceId(Long serviceId) {
        this.serviceId = serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_REFUND_APPLICATIONS.ORDER_NUMBER
     *
     * @return the value of OMS_REFUND_APPLICATIONS.ORDER_NUMBER
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_REFUND_APPLICATIONS.ORDER_NUMBER
     *
     * @param orderNumber the value for OMS_REFUND_APPLICATIONS.ORDER_NUMBER
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_REFUND_APPLICATIONS.STATUS
     *
     * @return the value of OMS_REFUND_APPLICATIONS.STATUS
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_REFUND_APPLICATIONS.STATUS
     *
     * @param status the value for OMS_REFUND_APPLICATIONS.STATUS
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_REFUND_APPLICATIONS.REFUND_TOTAL
     *
     * @return the value of OMS_REFUND_APPLICATIONS.REFUND_TOTAL
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public BigDecimal getRefundTotal() {
        return refundTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_REFUND_APPLICATIONS.REFUND_TOTAL
     *
     * @param refundTotal the value for OMS_REFUND_APPLICATIONS.REFUND_TOTAL
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setRefundTotal(BigDecimal refundTotal) {
        this.refundTotal = refundTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_REFUND_APPLICATIONS.REASON
     *
     * @return the value of OMS_REFUND_APPLICATIONS.REASON
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_REFUND_APPLICATIONS.REASON
     *
     * @param reason the value for OMS_REFUND_APPLICATIONS.REASON
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_REFUND_APPLICATIONS.CREATED_AT
     *
     * @return the value of OMS_REFUND_APPLICATIONS.CREATED_AT
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_REFUND_APPLICATIONS.CREATED_AT
     *
     * @param createdAt the value for OMS_REFUND_APPLICATIONS.CREATED_AT
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_REFUND_APPLICATIONS.UPDATED_AT
     *
     * @return the value of OMS_REFUND_APPLICATIONS.UPDATED_AT
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_REFUND_APPLICATIONS.UPDATED_AT
     *
     * @param updatedAt the value for OMS_REFUND_APPLICATIONS.UPDATED_AT
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}