package com.kawasaki.service.order_service.model;

import java.math.BigDecimal;
import java.util.Date;

public class Refund {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_REFUNDS.ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_REFUNDS.ORDER_ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_REFUNDS.REFUND_TOTAL
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    private BigDecimal refundTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_REFUNDS.STATUS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_REFUNDS.CREATED_AT
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OMS_REFUNDS.UPDATED_AT
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_REFUNDS.ID
     *
     * @return the value of OMS_REFUNDS.ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_REFUNDS.ID
     *
     * @param id the value for OMS_REFUNDS.ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_REFUNDS.ORDER_ID
     *
     * @return the value of OMS_REFUNDS.ORDER_ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_REFUNDS.ORDER_ID
     *
     * @param orderId the value for OMS_REFUNDS.ORDER_ID
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_REFUNDS.REFUND_TOTAL
     *
     * @return the value of OMS_REFUNDS.REFUND_TOTAL
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public BigDecimal getRefundTotal() {
        return refundTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_REFUNDS.REFUND_TOTAL
     *
     * @param refundTotal the value for OMS_REFUNDS.REFUND_TOTAL
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public void setRefundTotal(BigDecimal refundTotal) {
        this.refundTotal = refundTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_REFUNDS.STATUS
     *
     * @return the value of OMS_REFUNDS.STATUS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_REFUNDS.STATUS
     *
     * @param status the value for OMS_REFUNDS.STATUS
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_REFUNDS.CREATED_AT
     *
     * @return the value of OMS_REFUNDS.CREATED_AT
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_REFUNDS.CREATED_AT
     *
     * @param createdAt the value for OMS_REFUNDS.CREATED_AT
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OMS_REFUNDS.UPDATED_AT
     *
     * @return the value of OMS_REFUNDS.UPDATED_AT
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OMS_REFUNDS.UPDATED_AT
     *
     * @param updatedAt the value for OMS_REFUNDS.UPDATED_AT
     *
     * @mbg.generated Thu Aug 28 01:46:36 EDT 2025
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}