package com.kawasaki.service.order_service.mapper;

import com.kawasaki.service.order_service.model.Order;
import com.kawasaki.service.order_service.model.OrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_ORDERS
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    long countByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_ORDERS
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int deleteByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_ORDERS
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_ORDERS
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int insert(Order row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_ORDERS
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int insertSelective(Order row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_ORDERS
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    List<Order> selectByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_ORDERS
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    Order selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_ORDERS
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int updateByExampleSelective(@Param("row") Order row, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_ORDERS
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int updateByExample(@Param("row") Order row, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_ORDERS
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int updateByPrimaryKeySelective(Order row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_ORDERS
     *
     * @mbg.generated Sat Aug 30 15:17:49 EDT 2025
     */
    int updateByPrimaryKey(Order row);
}