package com.kawasaki.service.order_service.mapper;

import com.kawasaki.service.order_service.model.Payment;
import com.kawasaki.service.order_service.model.PaymentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_PAYMENTS
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    long countByExample(PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_PAYMENTS
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    int deleteByExample(PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_PAYMENTS
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_PAYMENTS
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    int insert(Payment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_PAYMENTS
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    int insertSelective(Payment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_PAYMENTS
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    List<Payment> selectByExample(PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_PAYMENTS
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    Payment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_PAYMENTS
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    int updateByExampleSelective(@Param("row") Payment row, @Param("example") PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_PAYMENTS
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    int updateByExample(@Param("row") Payment row, @Param("example") PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_PAYMENTS
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    int updateByPrimaryKeySelective(Payment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_PAYMENTS
     *
     * @mbg.generated Thu Jul 10 01:48:16 EDT 2025
     */
    int updateByPrimaryKey(Payment row);
}