package com.kawasaki.service.order_service.mapper;

import com.kawasaki.service.order_service.model.Refund;
import com.kawasaki.service.order_service.model.RefundExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RefundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_REFUNDS
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    long countByExample(RefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_REFUNDS
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int deleteByExample(RefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_REFUNDS
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_REFUNDS
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int insert(Refund row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_REFUNDS
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int insertSelective(Refund row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_REFUNDS
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    List<Refund> selectByExample(RefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_REFUNDS
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    Refund selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_REFUNDS
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int updateByExampleSelective(@Param("row") Refund row, @Param("example") RefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_REFUNDS
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int updateByExample(@Param("row") Refund row, @Param("example") RefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_REFUNDS
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int updateByPrimaryKeySelective(Refund row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_REFUNDS
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int updateByPrimaryKey(Refund row);
}