package com.kawasaki.service.order_service.mapper;

import com.kawasaki.service.order_service.model.RefundApplication;
import com.kawasaki.service.order_service.model.RefundApplicationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RefundApplicationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_REFUND_APPLICATIONS
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    long countByExample(RefundApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_REFUND_APPLICATIONS
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int deleteByExample(RefundApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_REFUND_APPLICATIONS
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_REFUND_APPLICATIONS
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int insert(RefundApplication row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_REFUND_APPLICATIONS
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int insertSelective(RefundApplication row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_REFUND_APPLICATIONS
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    List<RefundApplication> selectByExample(RefundApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_REFUND_APPLICATIONS
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    RefundApplication selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_REFUND_APPLICATIONS
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int updateByExampleSelective(@Param("row") RefundApplication row, @Param("example") RefundApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_REFUND_APPLICATIONS
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int updateByExample(@Param("row") RefundApplication row, @Param("example") RefundApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_REFUND_APPLICATIONS
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int updateByPrimaryKeySelective(RefundApplication row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OMS_REFUND_APPLICATIONS
     *
     * @mbg.generated Tue Jul 15 00:44:13 EDT 2025
     */
    int updateByPrimaryKey(RefundApplication row);
}